"""inintala

Revision ID: 39578c6f6be7
Revises: dba44e2ca6a5
Create Date: 2018-12-05 10:49:06.510812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39578c6f6be7'
down_revision = 'dba44e2ca6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_order', sa.Column('is_delected', sa.Boolean(), nullable=True))
    op.add_column('ihome_order', sa.Column('trade_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_order', 'trade_id')
    op.drop_column('ihome_order', 'is_delected')
    # ### end Alembic commands ###
