"""nsi

Revision ID: 3b06ac6b04b4
Revises: c331ce698ef1
Create Date: 2018-12-05 16:09:18.278621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b06ac6b04b4'
down_revision = 'c331ce698ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_order', 'trade_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_order', sa.Column('trade_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
