"""nsi

Revision ID: c331ce698ef1
Revises: 79a2c5634f65
Create Date: 2018-12-05 12:00:03.411189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c331ce698ef1'
down_revision = '79a2c5634f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_order', sa.Column('trade_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_order', 'trade_id')
    # ### end Alembic commands ###
