"""second

Revision ID: dba44e2ca6a5
Revises: 
Create Date: 2018-12-02 10:49:48.040129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba44e2ca6a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('is_delected', sa.Boolean(), nullable=True))
    op.drop_column('ihome_house', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_house', sa.Column('user_name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('ihome_house', 'is_delected')
    # ### end Alembic commands ###
