"""ht

Revision ID: e530d374f253
Revises: 6be063a3d564
Create Date: 2018-12-05 16:49:38.769433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e530d374f253'
down_revision = '6be063a3d564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_order', sa.Column('trade_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_order', 'trade_id')
    # ### end Alembic commands ###
